### ISSUE TITLE
Your contact information appears to be recursive. :-)

### ISSUE THREAD

**Issue by RichardJFoster** [aj-foster/aj-foster.com#2]
Greetings AJ. Trying to find the right way to contact you with a question about the Virtual Pit for FTC Meet 4. Your website's "About" page says to reach out to you via social media and links to Twitter. On Twitter, your profile says "Use website to contact me".

(Apologies in advance if your website is actually trying to do something clever that is being blocked by the corporate firewall I'm stuck behind. I couldn't see anything, but I've not played with Elixir.)

If Twitter is the correct mechanism, feel free to DM me there.

**Comment by aj-foster** [comment]
Hello there 👋🏼  Similarly it looks like I'm unable to DM you on Twitter. 🙂 Glad to see communication in 2021 is so straightforward.

**Comment by RichardJFoster** [comment]
D'oh! Yup. I've now followed you over there which should hopefully open the DM gateway. Isn't technology wonderful! (Especially when trying not to share too much information in a public forum.)
