### ISSUE TITLE
Favicon bigger than it needs to be

### ISSUE THREAD

**Issue by mig4ng** [aj-foster/aj-foster.com#3]
Not really an issue, it is more a nice to have improvement, your favicon is kind of big for what it needs to be.
E.g. loading https://aj-foster.com/2021/absinthe-apollo-swift/ out of 273.41 KB transferred 198.71 KB is the favicon.

Found this because I really liked the font you are using and went to the inspector to check it, and noticed that despite the website being super fast to load and render the main size of the page came from this single favicon.

Great website ❤️

**Comment by aj-foster** [comment]
Hello there!

Thanks for stopping by and taking the time to let me know about this. I've regenerated the favicon file so that it's much more reasonably sized, and even threw in some Apple & Android touch icons.

Good catch :)

(Note to self: 6d59fbc)
